#!/usr/bin/python
# -*- coding: utf-8 -*-

# File Renamer - Lists
#
# Author: Simon Lachaîne


CUSTOM_NOTES = [
    ("", "", ""),
    ("Airline", "AIR", "AIR"),
    ("AU exclusive", "AUSx", "AUSx"),
    ("Blu-ray exclusive", "BDx", "BDx"),
    ("CAN exclusive", "CANx", "CANx"),
    ("Censored", "CSR", "CSR"),
    ("Clean VOD version", "VOD", "VOD"),
    ("Library Version", "LIB", "LIB"),
    ("Cinavia", "CINAVIA", "CINAVIA"),
    ("Non-Cinavia", "NCINAVIA", "NCINAVIA"),
    ("Director's Cut", "DIR", "DIR"),
    ("Extended Cut", "EXT", "DNC"),
    ("Downconvert", "DNC", "DNC"),
    ("DVD exclusive", "DVDx", "DVDx"),
    ("International", "INTL", "INTL"),
    ("Unsubtitled", "UNSUB", "UNSUB"),
    ("Pillarbox", "PBX", "PBX"),
    ("Short Episode", "SHEP", "SHEP"),
    ("Slate", "SLATE", "SLATE"),
    ("SPA exclusive", "SPAx", "SPAx"),
    ("Store exclusive", "STOREx", "STOREx"),
    ("Textless", "TXTL", "TXTL"),
    ("With Textless (Muse)", "WTXTL", "WTXTL"),
    ("Theatre exclusive", "THRx", "THRx"),
    ("UK exclusive", "UKx", "UKx"),
    ("Unrated", "URT", "URT"),
    ("Upconvert", "UPC", "UPC"),
    ("US exclusive", "USAx", "USAx"),
    ("Web exclusive", "WEBx", "WEBx"),
    ("3D Left Eye", "3DLE", "3DLE"),
    ("3D Right Eye", "3DRE", "3DRE"),
    ("Graphical Content", "GRAC", "GRAC"),
    ("QC Report", "QC", "qc_report"),
    ("Poster Art", "POSTER", "POSTER"),
    ("Chapter Still 01", "CHAP01", "CHAP01"),
    ("Chapter Still 02", "CHAP02", "CHAP02"),
    ("Chapter Still 03", "CHAP03", "CHAP03"),
    ("Chapter Still 04", "CHAP04", "CHAP04"),
    ("Chapter Still 05", "CHAP05", "CHAP05"),
    ("Chapter Still 06", "CHAP06", "CHAP06"),
    ("Chapter Still 07", "CHAP07", "CHAP07"),
    ("Chapter Still 08", "CHAP08", "CHAP08"),
    ("Chapter Still 09", "CHAP09", "CHAP09"),
    ("Chapter Still 10", "CHAP10", "CHAP10"),
    ("Chapter Still 11", "CHAP11", "CHAP11"),
    ("Chapter Still 12", "CHAP12", "CHAP12"),
    ("Chapter Still 13", "CHAP13", "CHAP13"),
    ("Chapter Still 14", "CHAP14", "CHAP14"),
    ("Chapter Still 15", "CHAP15", "CHAP15"),
    ("10 Minutes segment", "10M", "10M"),
    ("15 Minutes segment", "15M", "15M"),
    ("30 Minutes segment", "30M", "30M"),
    ("60 Minutes segment", "60M", "60M"),
    ("90 Minutes segment", "90M", "90M"),
    ("120 Minutes segment", "120M", "120M"),
]


CUSTOM_CONTENT = [
    ("Feature", "FTR", "ftr"),
    ("Trailer", "TLR", "trl"),
    ("Teaser", "TSR", "tsr"),
    ("Episodic (Sxxx_Exxx)", "S", "s"),
    ("Volume (VOLxxx_Exxx)", "VOL", "vol"),
    ("Electronic Press Kit", "EPK", "epk"),
    ("Deleted Scenes", "SCEN", "scen"),
    ("Bloopers", "BLO", "blo"),
    ("Making-of", "MKO", "mko"),
    ("Featurette", "FTT", "ftt"),
    ("Behind the Scenes", "BTS", "bts"),
    ("Interview", "ITV", "itv"),
    ("Audio Commentary", "COM", "com"),
    ("Music Video", "MUS", "mus"),
    ("Clip", "CLP", "clp"),
    ("Preview", "PVW", "pvw"),
    ("Rating Card", "RTC", "rtc"),
    ("15s Spot", "ADV15", "adv15"),
    ("30s Spot", "ADV30", "adv30"),
    ("60s Spot", "ADV60", "adv60")
]


CODECS = [
    ("Audio", "AUDIO"),
    ("IMF", "IMF"),
    ("JPEG", "JPEG"),
    ("MPEG", "MPEG"),
    ("MXF", "MXF"),
    ("ProRes 422", "PR42"),
    ("ProRes 422 HQ", "PRHQ"),
    ("ProRes 422 LT", "PRLT"),
    ("ProRes 422 Proxy", "PRPX"),
    ("ProRes 4444", "PR44"),
    ("ProRes 4444 XQ", "PRXQ"),
    ("Uncompress", "UNC")
]


MA_RESOLUTIONS = [
    "1920x1080",
    "1280x720",
]


MEZZ_RESOLUTIONS = [
    "1280x720",
    "NTSC 16:9 SD",
    "NTSC 4:3 SD",
]


CUSTOM_RESOLUTIONS = [
    ("1920x1080", "1080", "hd-"),
    ("1280x720", "720", "hd720-"),
    ("NTSC 16:9 SD", "NTSC16", "ntsc16-"),
    ("NTSC 4:3 SD", "NTSC43", "ntsc43-"),
    ("PAL 16:9 SD", "PAL16", "pal16-"),
    ("PAL 4:3 SD", "PAL43", "pal43-"),
    ("4K", "4K", "4k-"),
    ("2K", "2K", "2k-"),
    ("UHD", "UHD", "uhd-"),
]


RATIOS = [
    ("2.40:1", "240"),
    ("2.39:1", "239"),
    ("2.35:1", "235"),
    ("1.85:1", "185"),
    ("1.78:1", "178"),
    ("1.66:1", "166"),
    ("1.33:1", "133"),
]


SPEED = [
    ("23.98p", "2398p"),
    ("24p", "24p"),
    ("25p", "25p"),
    ("25i", "25i"),
    ("29.97i Drop Frame", "2997i-DF"),
    ("29.97i Non-Drop Frame", "2997i-NDF"),
    ("29.97p Drop Frame", "2997p-DF"),
    ("29.97p Non-Drop Frame", "2997p-NDF"),
    ("30p", "30p"),
    ("30i", "30i"),
    ("48p", "48p"),
    ("50i", "50i"),
    ("59.94i Drop Frame", "5994i-DF"),
    ("59.94i Non-Drop Frame", "5994i-NDF"),
    ("59.94p Drop Frame", "5994p-DF"),
    ("59.94p Non-Drop Frame", "5994p-NDF"),
    ("60p", "60p"),
    ("60i", "60i")
]


SUB_NOTES = [
    ("", ""),
    ("CC - Full (dialogues & Inserts)", "CC_FULL"),
    ("CC - Partial Subtitles", "CC_PART"),
    ("CC - Dialogues only", "CC_DIA"),
    ("CC - Full with hearing-impaired details", "CC_SDH"),
    ("CC - Narratives", "CC_NAR"),
    ("Subtitles - Full (dialogues & Inserts)", "SUB_FULL"),
    ("Subtitles - Partial Subtitles", "SUB_PART"),
    ("Subtitles - Dialogues only", "SUB_DIA"),
    ("Subtitles - Full with hearing-impaired details", "SUB_SDH"),
    ("Subtitles - Narratives", "SUB_NAR"),
]


CUSTOM_EXTENSIONS = [
    ".mov",
    ".mxf",
    ".mp4",
    ".mpeg",
    ".wav",
    ".aiff",
    ".scc",
    ".itt",
    ".stl",
    ".xml",
    ".txt",
    ".doc",
    ".docx",
    ".srt",
    ".cap",
    ".aaf",
    ".ult",
    ".smi",
    ".asc",
    ".xls",
    ".xlsx",
    ".jpg",
    ".png",
    ".tif",
    ".psd",
    ".tga",
    ".pdf",
]


FACILITY = [
    (unicode("Montréal", encoding="utf-8"), unicode("MTL", encoding="utf-8")),
    ("Pinewood", "PNW"),
    ("Sydney", "SYD"),
    ("Glendale", "GLE"),
    ("Toronto", "TRO"),
    ("Bangalore", "BGR"),
]


AUDIO_CONFIGS = [
    ("5.1 Surround", "51"),
    ("7.1 Surround", "71"),
    ("Total Mix (LtRt)", "LtRt"),
    ("Stereo Mix", "20"),
    ("DTS", "DTS"),
    ("DolbyE", "DolbyE"),
    ("DolbyEX", "DolbyEX"),
    ("Mono track", "MONO"),
    ("Unused (MOS)", "MOS"),
    ("Music & Effects", "ME"),
    ("Narrator", "NAR"),
    ("Dialogue", "DIA"),
    ("Music", "MUS"),
    ("Effects", "FX"),
    ("Mix Minus Narrator", "MMN"),
    ("Descriptive Video", "DV"),
    ("Stereo Narrator", "STNAR"),
    ("Stereo Dialogue", "STDIA"),
    ("Stereo Music", "STMUS"),
    ("Stereo Effects", "STFX"),
    ("5.1 Music & Effects", "51ME"),
    ("5.1 Unconventional", "51x")
]


LANGUAGES = [
    ("N/A", "xx", "XX"),
    ("Afrikaans", "af", "AF"),
    ("Arabic", "ar", "AR"),
    ("Bosnian", "bs", "BS"),
    ("Bulgarian", "bg", "BG"),
    ("Cantonese (script)", "yueHant", "yueHant"),
    ("Cantonese (spoken)", "yue", "YUE"),
    ("Catalan", "ca", "CA"),
    ("Croatian", "hr", "HR"),
    ("Czech", "cs", "CS"),
    ("Danish", "da", "DA"),
    ("Dutch (Belgium)", "nlBE", "nlBE"),
    ("Dutch (Netherlands)", "nlNL", "nlNL"),
    ("English", "en", "----"),
    ("English (Australia)", "enAU", "enAU"),
    ("English (Canada)", "enCA", "enCA"),
    ("English (Ireland)", "enIE", "enIE"),
    ("English (New Zealand)", "enNZ", "enNZ"),
    ("English (United Kingdom)", "enGB", "enGB"),
    ("English (United States)", "enUS", "enUS"),
    ("Estonian", "et", "ET"),
    ("Fārsi", "fa", "FA"),
    ("Finnish", "fi", "FI"),
    ("Flemmish", "vl", "VL"),
    ("French", "fr", "----"),
    ("French (Belgium)", "frBE", "frBE"),
    ("French (Canada)", "frCA", "frCA"),
    ("French (France)", "frFR", "frFR"),
    ("French (Switzerland)", "frCH", "frCH"),
    ("German (Austria)", "deAT", "deAT"),
    ("German (Germany)", "deDE", "deDE"),
    ("German (Switzerland)", "deCH", "deCH"),
    ("Greek", "el", "EL"),
    ("Greek (Cyprus)", "elCY", "elCY"),
    ("Hebrew", "he", "HE"),
    ("Hindi", "hi", "HI"),
    ("Hungarian", "hu", "HU"),
    ("Icelandic", "is", "IS"),
    ("Indonesian", "id", "ID"),
    ("Inuktitut", "iu", "IU"),
    ("Italian", "it", "IT"),
    ("Japanese", "ja", "JA"),
    ("Kazakh", "kk", "KK"),
    ("Korean", "ko", "KO"),
    ("Lao", "lo", "LO"),
    ("Latvian", "lv", "LV"),
    ("Lithuanian", "lt", "LT"),
    ("Luxembourgish", "lb", "LB"),
    ("Malay", "ms", "MS"),
    ("Maltese", "mt", "MT"),
    ("Mandarin (simplified script)", "cmnHans", "cmnHans"),
    ("Mandarin (spoken)", "cmn", "CMN"),
    ("Mandarin (traditional script)", "cmnHant", "cmnHant"),
    ("Norwegian", "no", "NO"),
    ("Polish", "pl", "PL"),
    ("Portuguese (Brazil)", "ptBR", "ptBR"),
    ("Portuguese (Portugal)", "ptPT", "ptPT"),
    ("Romanian", "ro", "RO"),
    ("Russian", "ru", "RU"),
    ("Serbian", "sr", "SR"),
    ("Slovak", "sk", "SK"),
    ("Slovenian", "sl", "SL"),
    ("Spanish (Latin America)", "es419", "es419"),
    ("Spanish (Mexico)", "esMX", "esMX"),
    ("Spanish (Spain)", "esES", "esES"),
    ("Swahili", "sw", "SW"),
    ("Swedish", "sv", "SV"),
    ("Tagalog", "tl", "TL"),
    ("Tamil", "ta", "TA"),
    ("Telugu", "te", "TE"),
    ("Thai", "th", "TH"),
    ("Turkish", "tr", "TR"),
    ("Ukrainian", "uk", "UK"),
    ("Urdu", "ur", "UR"),
    ("Vietnamese", "vi", "VI"),
    ("Zulu", "zu", "ZU"),
]
