CUSTOM_NOTES = [
    ("", "", ""),
    ("Airline", "AIR", "AIR"),
    ("AU exclusive", "AUSx", "AUSx"),
    ("Blu-ray exclusive", "BDx", "BDx"),
    ("CAN exclusive", "CANx", "CANx"),
    ("Censored", "CSR", "CSR"),
    ("Clean VOD version", "VOD", "VOD"),
    ("Library Version", "LIB", "LIB"),
    ("Cinavia", "CINAVIA", "CINAVIA"),
    ("Non-Cinavia", "NCINAVIA", "NCINAVIA"),
    ("Director's Cut", "DIR", "DIR"),
    ("Extended Cut", "EXT", "DNC"),
    ("Downconvert", "DNC", "DNC"),
    ("DVD exclusive", "DVDx", "DVDx"),
    ("International", "INTL", "INTL"),
    ("Unsubtitled", "UNSUB", "UNSUB"),
    ("Pillarbox", "PBX", "PBX"),
    ("Short Episode", "SHEP", "SHEP"),
    ("Slate", "SLATE", "SLATE"),
    ("SPA exclusive", "SPAx", "SPAx"),
    ("Store exclusive", "STOREx", "STOREx"),
    ("Textless", "TXTL", "TXTL"),
    ("With Textless (Muse)", "WTXTL", "WTXTL"),
    ("Theatre exclusive", "THRx", "THRx"),
    ("UK exclusive", "UKx", "UKx"),
    ("Unrated", "URT", "URT"),
    ("Upconvert", "UPC", "UPC"),
    ("US exclusive", "USAx", "USAx"),
    ("Web exclusive", "WEBx", "WEBx"),
    ("3D Left Eye", "3DLE", "3DLE"),
    ("3D Right Eye", "3DRE", "3DRE"),
    ("Graphical Content", "GRAC", "GRAC"),
    ("QC Report", "QC", "qc_report"),
    ("Poster Art", "POSTER", "POSTER"),
    ("Chapter Still 01", "CHAP01", "CHAP01"),
    ("Chapter Still 02", "CHAP02", "CHAP02"),
    ("Chapter Still 03", "CHAP03", "CHAP03"),
    ("Chapter Still 04", "CHAP04", "CHAP04"),
    ("Chapter Still 05", "CHAP05", "CHAP05"),
    ("Chapter Still 06", "CHAP06", "CHAP06"),
    ("Chapter Still 07", "CHAP07", "CHAP07"),
    ("Chapter Still 08", "CHAP08", "CHAP08"),
    ("Chapter Still 09", "CHAP09", "CHAP09"),
    ("Chapter Still 10", "CHAP10", "CHAP10"),
    ("Chapter Still 11", "CHAP11", "CHAP11"),
    ("Chapter Still 12", "CHAP12", "CHAP12"),
    ("Chapter Still 13", "CHAP13", "CHAP13"),
    ("Chapter Still 14", "CHAP14", "CHAP14"),
    ("Chapter Still 15", "CHAP15", "CHAP15"),
    ("10 Minutes segment", "10M", "10M"),
    ("15 Minutes segment", "15M", "15M"),
    ("30 Minutes segment", "30M", "30M"),
    ("60 Minutes segment", "60M", "60M"),
    ("90 Minutes segment", "90M", "90M"),
    ("120 Minutes segment", "120M", "120M"),
]


CUSTOM_CONTENT = [
    ("Feature", "FTR", "FTR"),
    ("Trailer", "TLR", "TRL"),
    ("Teaser", "TSR", "TSR"),
    ("Episodic (Sxxx_Exxx)", "S", "S"),
    ("Volume (VOLxxx_Exxx)", "VOL", "VOL"),
    ("Electronic Press Kit", "EPK", "EPK"),
    ("Deleted Scenes", "SCEN", "SCEN"),
    ("Bloopers", "BLO", "BLO"),
    ("Making-of", "MKO", "MKO"),
    ("Featurette", "FTT", "FTT"),
    ("Behind the Scenes", "BTS", "BTS"),
    ("Interview", "ITV", "ITV"),
    ("Audio Commentary", "COM", "COM"),
    ("Music Video", "MUS", "MUS"),
    ("Clip", "CLP", "CLP"),
    ("Preview", "PVW", "PVW"),
    ("Rating Card", "RTC", "RTC"),
    ("15s Spot", "ADV15", "ADV15"),
    ("30s Spot", "ADV30", "ADV30"),
    ("60s Spot", "ADV60", "ADV60")
]


MA_RESOLUTIONS = [
    "1920x1080",
    "1280x720",
]


MEZZ_RESOLUTIONS = [
    "1280x720",
    "NTSC 16:9 SD",
    "NTSC 4:3 SD",
]


CUSTOM_RESOLUTIONS = [
    ("1920x1080", "1080", "hd"),
    ("1280x720", "720", "hd720"),
    ("NTSC 16:9 SD", "NTSC16", "NTSC16"),
    ("NTSC 4:3 SD", "NTSC43", "NTSC43"),
    ("PAL 16:9 SD", "PAL16", "PAL16"),
    ("PAL 4:3 SD", "PAL43", "PAL43"),
    ("4K", "4K", "4K"),
    ("2K", "2K", "2K"),
    ("UHD", "UHD", "UHD"),
]


CUSTOM_EXTENSIONS = [
    ".mov",
    ".mxf",
    ".mp4",
    ".mpeg",
    ".wav",
    ".aiff",
    ".scc",
    ".itt",
    ".stl",
    ".xml",
    ".txt",
    ".doc",
    ".docx",
    ".srt",
    ".cap",
    ".aaf",
    ".ult",
    ".smi",
    ".asc",
    ".xls",
    ".xlsx",
    ".jpg",
    ".png",
    ".tif",
    ".psd",
    ".tga",
    ".pdf",
]


AUDIO_CONFIGS = [
    ("5.1 Surround", "51"),
    ("7.1 Surround", "71"),
    ("Total Mix (LtRt)", "LtRt"),
    ("Stereo Mix", "20"),
    ("DTS", "DTS"),
    ("DolbyE", "DolbyE"),
    ("DolbyEX", "DolbyEX"),
    ("Mono track", "MONO"),
    ("Unused (MOS)", "MOS"),
    ("Music & Effects", "ME"),
    ("Narrator", "NAR"),
    ("Dialogue", "DIA"),
    ("Music", "MUS"),
    ("Effects", "FX"),
    ("Mix Minus Narrator", "MMN"),
    ("Descriptive Video", "DV"),
    ("Stereo Narrator", "STNAR"),
    ("Stereo Dialogue", "STDIA"),
    ("Stereo Music", "STMUS"),
    ("Stereo Effects", "STFX"),
    ("5.1 Music & Effects", "51ME"),
    ("5.1 Unconventional", "51x")
]
