# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'filerenamerwindow.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FileRenamerWindow(object):
    def setupUi(self, FileRenamerWindow):
        FileRenamerWindow.setObjectName("FileRenamerWindow")
        FileRenamerWindow.resize(944, 881)
        self.centralWidget = QtWidgets.QWidget(FileRenamerWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.year_lbl = QtWidgets.QDateEdit(self.frame)
        self.year_lbl.setDate(QtCore.QDate(2017, 1, 1))
        self.year_lbl.setObjectName("year_lbl")
        self.gridLayout_2.addWidget(self.year_lbl, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 8, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 5, 0, 1, 1)
        self.trailer_nb_line = QtWidgets.QLineEdit(self.frame)
        self.trailer_nb_line.setObjectName("trailer_nb_line")
        self.gridLayout_2.addWidget(self.trailer_nb_line, 4, 1, 1, 1)
        self.notes_combo = QtWidgets.QComboBox(self.frame)
        self.notes_combo.setObjectName("notes_combo")
        self.gridLayout_2.addWidget(self.notes_combo, 2, 1, 1, 1)
        self.content_combo = QtWidgets.QComboBox(self.frame)
        self.content_combo.setObjectName("content_combo")
        self.gridLayout_2.addWidget(self.content_combo, 3, 1, 1, 1)
        self.trailer_pass_line = QtWidgets.QLineEdit(self.frame)
        self.trailer_pass_line.setObjectName("trailer_pass_line")
        self.gridLayout_2.addWidget(self.trailer_pass_line, 5, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.reel_line = QtWidgets.QLineEdit(self.frame)
        self.reel_line.setObjectName("reel_line")
        self.gridLayout_2.addWidget(self.reel_line, 8, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 3, 0, 1, 1)
        self.episode_nb_line = QtWidgets.QLineEdit(self.frame)
        self.episode_nb_line.setObjectName("episode_nb_line")
        self.gridLayout_2.addWidget(self.episode_nb_line, 7, 1, 1, 1)
        self.season_nb_line = QtWidgets.QLineEdit(self.frame)
        self.season_nb_line.setObjectName("season_nb_line")
        self.gridLayout_2.addWidget(self.season_nb_line, 6, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 6, 0, 1, 1)
        self.version_line = QtWidgets.QLineEdit(self.frame)
        self.version_line.setObjectName("version_line")
        self.gridLayout_2.addWidget(self.version_line, 9, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 7, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 9, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 2, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.default_ma = QtWidgets.QRadioButton(self.groupBox)
        self.default_ma.setObjectName("default_ma")
        self.horizontalLayout.addWidget(self.default_ma)
        self.default_mezz = QtWidgets.QRadioButton(self.groupBox)
        self.default_mezz.setChecked(True)
        self.default_mezz.setObjectName("default_mezz")
        self.horizontalLayout.addWidget(self.default_mezz)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 2)
        self.frame_3 = QtWidgets.QFrame(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_20 = QtWidgets.QLabel(self.frame_3)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_2.addWidget(self.label_20)
        self.add_config_btn = QtWidgets.QPushButton(self.frame_3)
        self.add_config_btn.setObjectName("add_config_btn")
        self.horizontalLayout_2.addWidget(self.add_config_btn)
        self.del_config_btn = QtWidgets.QPushButton(self.frame_3)
        self.del_config_btn.setObjectName("del_config_btn")
        self.horizontalLayout_2.addWidget(self.del_config_btn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.audio_lyt = QtWidgets.QGridLayout()
        self.audio_lyt.setContentsMargins(11, 11, 11, 11)
        self.audio_lyt.setSpacing(6)
        self.audio_lyt.setObjectName("audio_lyt")
        self.horizontalLayout_3.addLayout(self.audio_lyt)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout.addWidget(self.frame_3, 3, 0, 1, 2)
        self.frame_2 = QtWidgets.QFrame(self.centralWidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_15 = QtWidgets.QLabel(self.frame_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 4, 0, 1, 1)
        self.codec_combo = QtWidgets.QComboBox(self.frame_2)
        self.codec_combo.setObjectName("codec_combo")
        self.gridLayout_3.addWidget(self.codec_combo, 0, 1, 1, 1)
        self.resolution_combo = QtWidgets.QComboBox(self.frame_2)
        self.resolution_combo.setObjectName("resolution_combo")
        self.gridLayout_3.addWidget(self.resolution_combo, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frame_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 1, 0, 1, 1)
        self.extension_combo = QtWidgets.QComboBox(self.frame_2)
        self.extension_combo.setObjectName("extension_combo")
        self.gridLayout_3.addWidget(self.extension_combo, 7, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.frame_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 6, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.frame_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 5, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.frame_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 2, 0, 1, 1)
        self.ratio_combo = QtWidgets.QComboBox(self.frame_2)
        self.ratio_combo.setObjectName("ratio_combo")
        self.gridLayout_3.addWidget(self.ratio_combo, 2, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.frame_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 3, 0, 1, 1)
        self.sub_language_combo = QtWidgets.QComboBox(self.frame_2)
        self.sub_language_combo.setObjectName("sub_language_combo")
        self.gridLayout_3.addWidget(self.sub_language_combo, 5, 1, 1, 1)
        self.speed_combo = QtWidgets.QComboBox(self.frame_2)
        self.speed_combo.setObjectName("speed_combo")
        self.gridLayout_3.addWidget(self.speed_combo, 3, 1, 1, 1)
        self.audio_language_combo = QtWidgets.QComboBox(self.frame_2)
        self.audio_language_combo.setObjectName("audio_language_combo")
        self.gridLayout_3.addWidget(self.audio_language_combo, 4, 1, 1, 1)
        self.sub_notes_combo = QtWidgets.QComboBox(self.frame_2)
        self.sub_notes_combo.setObjectName("sub_notes_combo")
        self.gridLayout_3.addWidget(self.sub_notes_combo, 6, 1, 1, 1)
        self.facility_combo = QtWidgets.QComboBox(self.frame_2)
        self.facility_combo.setObjectName("facility_combo")
        self.gridLayout_3.addWidget(self.facility_combo, 8, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.frame_2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 7, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.frame_2)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 8, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_2, 2, 1, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.centralWidget)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.results_line = QtWidgets.QLineEdit(self.frame_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.results_line.setFont(font)
        self.results_line.setObjectName("results_line")
        self.horizontalLayout_4.addWidget(self.results_line)
        self.lcd = QtWidgets.QLCDNumber(self.frame_4)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        self.lcd.setPalette(palette)
        self.lcd.setAutoFillBackground(True)
        self.lcd.setDigitCount(3)
        self.lcd.setObjectName("lcd")
        self.horizontalLayout_4.addWidget(self.lcd)
        self.copy_btn = QtWidgets.QPushButton(self.frame_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.copy_btn.setFont(font)
        self.copy_btn.setObjectName("copy_btn")
        self.horizontalLayout_4.addWidget(self.copy_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.validation_text = QtWidgets.QPlainTextEdit(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.validation_text.sizePolicy().hasHeightForWidth())
        self.validation_text.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.validation_text.setFont(font)
        self.validation_text.setObjectName("validation_text")
        self.verticalLayout_2.addWidget(self.validation_text)
        self.gridLayout.addWidget(self.frame_4, 4, 0, 1, 2)
        self.frame_5 = QtWidgets.QFrame(self.centralWidget)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.frame_5)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.title_line = QtWidgets.QLineEdit(self.frame_5)
        self.title_line.setObjectName("title_line")
        self.horizontalLayout_5.addWidget(self.title_line)
        self.gridLayout.addWidget(self.frame_5, 1, 0, 1, 2)
        FileRenamerWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(FileRenamerWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 944, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        FileRenamerWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(FileRenamerWindow)
        self.statusBar.setObjectName("statusBar")
        FileRenamerWindow.setStatusBar(self.statusBar)
        self.actionAbout = QtWidgets.QAction(FileRenamerWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionQuit = QtWidgets.QAction(FileRenamerWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionAbout)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(FileRenamerWindow)
        QtCore.QMetaObject.connectSlotsByName(FileRenamerWindow)

    def retranslateUi(self, FileRenamerWindow):
        _translate = QtCore.QCoreApplication.translate
        FileRenamerWindow.setWindowTitle(_translate("FileRenamerWindow", "File Renamer"))
        self.year_lbl.setDisplayFormat(_translate("FileRenamerWindow", "yyyy"))
        self.label_10.setText(_translate("FileRenamerWindow", "Reel #"))
        self.label_7.setText(_translate("FileRenamerWindow", "Trailer pass #"))
        self.label_4.setText(_translate("FileRenamerWindow", "Notes"))
        self.label_6.setText(_translate("FileRenamerWindow", "Trailer #/ Teaser #"))
        self.label_3.setText(_translate("FileRenamerWindow", "Year"))
        self.label_5.setText(_translate("FileRenamerWindow", "Type of content"))
        self.label_8.setText(_translate("FileRenamerWindow", "Season # / Volume #"))
        self.label_9.setText(_translate("FileRenamerWindow", "Episode #"))
        self.label_11.setText(_translate("FileRenamerWindow", "Version"))
        self.groupBox.setTitle(_translate("FileRenamerWindow", "Platform"))
        self.default_ma.setText(_translate("FileRenamerWindow", "MediAffinity"))
        self.default_mezz.setText(_translate("FileRenamerWindow", "Mezz"))
        self.label_20.setText(_translate("FileRenamerWindow", "Audio configuration"))
        self.add_config_btn.setText(_translate("FileRenamerWindow", "Add configuration"))
        self.del_config_btn.setText(_translate("FileRenamerWindow", "Remove configuration"))
        self.label_15.setText(_translate("FileRenamerWindow", "Audio language"))
        self.label_2.setText(_translate("FileRenamerWindow", "Codec"))
        self.label_12.setText(_translate("FileRenamerWindow", "Resolution"))
        self.label_17.setText(_translate("FileRenamerWindow", "Subtitle notes"))
        self.label_16.setText(_translate("FileRenamerWindow", "Subtitle language"))
        self.label_13.setText(_translate("FileRenamerWindow", "Aspect ratio"))
        self.label_14.setText(_translate("FileRenamerWindow", "Speed"))
        self.label_18.setText(_translate("FileRenamerWindow", "Extension"))
        self.label_19.setText(_translate("FileRenamerWindow", "Facility"))
        self.copy_btn.setText(_translate("FileRenamerWindow", "Copy"))
        self.label.setText(_translate("FileRenamerWindow", "Title"))
        self.menuFile.setTitle(_translate("FileRenamerWindow", "File"))
        self.actionAbout.setText(_translate("FileRenamerWindow", "About"))
        self.actionQuit.setText(_translate("FileRenamerWindow", "Quit"))

